spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_ordering_system
    username: root
    password: localhost@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false
  mvc:
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

logging:
  level:
    root: info
    org.hibernate.SQL: debug
